### ISSUE TITLE
INFRASTRUCTURE - Keep List of Servers

### ISSUE THREAD

**Issue by richraid21** [sqreen/CTOSecurityChecklist#13]
This is currently marked as Series A, but why would you not keep a list of your servers/services from initial company creation? If for nothing else than security audits.

**Comment by aviat** [comment]
@richraid21 everything in this list is doable from the initial company creation. But at that point, your infrastructure tend to be very small and to change a lot. Hence, it does not make that much sense to me to start a formal list at that time.
