### ISSUE TITLE
HTTP 404 on "Ensure your domain names are secured" read more link

### ISSUE THREAD

**Issue by incyclum** [sqreen/CTOSecurityChecklist#18]
http://www.esecurityplanet.com/views/3928456/8-Tips-for-Protecting-Your-Domain-Names.htm

**Comment by Kingeek** [comment]
Hey @incyclum ✋
I don't understand. You have linked a broken url when our link work.
What's your point here?

**Comment by incyclum** [comment]
Ah sorry, I probably made a mistake. I'm pretty sure I copy-pasted this link in the first comment.

Anyway. Unreproductible bug.
